{{- if and .Values.web.enabled .Values.web.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "terrapod.fullname" . }}-web
  labels:
    {{- include "terrapod.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  {{- if .Values.web.pdb.minAvailable }}
  minAvailable: {{ .Values.web.pdb.minAvailable }}
  {{- else }}
  maxUnavailable: {{ .Values.web.pdb.maxUnavailable | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "terrapod.web.selectorLabels" . | nindent 6 }}
{{- end }}
