{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "terrapod.fullname" . }}-web
  labels:
    {{- include "terrapod.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
  {{- with .Values.web.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.web.service.type | default "ClusterIP" }}
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.api.config.metrics.enabled }}
    - port: 9091
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "terrapod.web.selectorLabels" . | nindent 4 }}
{{- end }}
