{{- if ne .Values.api.enabled false }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "terrapod.fullname" . }}-api
  labels:
    {{- include "terrapod.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.api.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.api.service.type | default "ClusterIP" }}
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "terrapod.api.selectorLabels" . | nindent 4 }}
{{- end }}
