"""Add private_key_encrypted column to gpg_keys for auto-signing.

Stores the Fernet-encrypted private key for auto-generated GPG signing keys.
Only populated for keys generated by Terrapod; user-uploaded keys will have
this column NULL.

Revision ID: c4fc090289ee
Revises: 851c0ca75afe
Create Date: 2026-03-05
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "c4fc090289ee"
down_revision: Union[str, None] = "851c0ca75afe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "gpg_keys",
        sa.Column("private_key_encrypted", sa.Text(), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("gpg_keys", "private_key_encrypted")
