"""Inject `h1:` hashes from Terrapod's provider mirror into the
runner's `.terraform.lock.hcl`.

Replaces the `tofu providers lock -platform=<other_arch>` invocation
in the bash entrypoint (v0.31.6: only-other-arch mitigation). Where
that command costs one full archive download per provider per plan,
this module makes one ~1 KB JSON request per provider — the mirror
already cached the archive and computed h1 server-side, so the
runner just splices the returned hash into the lock.

Algorithm:

  1. Read .terraform.lock.hcl, parse it into per-provider blocks.
  2. For each provider block:
     a. GET /v1/providers/{hostname}/{namespace}/{type}/{version}.json
        from Terrapod's mirror.
     b. Pull the `h1:` hash for `<other_arch>` from
        `archives.<platform>.hashes`. (Skip if absent — uncached
        provider; mirror only knew the upstream zh:.)
     c. Splice the `h1:` line into the provider's `hashes = [...]`
        list, preserving existing entries.
  3. Write the file back.

If any provider couldn't be resolved (mirror missed it AND we want
strict apply-time guarantees), the caller can fall back to
`tofu providers lock -platform=<other_arch>` for that specific
provider. This module just does the cheap path; the fallback is
the bash entrypoint's job.
"""

from __future__ import annotations

import platform
import re
from dataclasses import dataclass
from pathlib import Path

import httpx
import structlog

logger = structlog.get_logger("runner.lock_extender")


# Match a provider block:
#   provider "<source>" {
#       version     = "<version>"
#       constraints = "<...>"
#       hashes = [
#           "h1:...",
#           "zh:...",
#       ]
#   }
#
# Greedy match of the body up to the closing `}` that lines up with
# the `provider "..." {` opener. HCL lock files are mechanically
# generated by tofu/terraform so we don't have to handle pathological
# indentation — every block looks the same shape.
_PROVIDER_BLOCK_RE = re.compile(
    r'(?P<header>provider\s+"(?P<source>[^"]+)"\s*\{\s*\n)'
    r"(?P<body>.*?)"
    r"(?P<close>\n\s*\})",
    re.DOTALL,
)

_VERSION_RE = re.compile(r'^\s*version\s*=\s*"(?P<version>[^"]+)"', re.MULTILINE)
_HASHES_OPEN_RE = re.compile(r"^(?P<indent>\s*)hashes\s*=\s*\[\s*\n", re.MULTILINE)


@dataclass(frozen=True)
class ProviderBlock:
    """One provider entry from .terraform.lock.hcl."""

    source: str  # e.g. "registry.opentofu.org/hashicorp/aws"
    version: str
    block_text: str  # the raw source of the entire `provider "..." {...}` block
    block_start: int  # start offset in the lock-file text
    block_end: int  # end offset (exclusive)

    @property
    def hostname(self) -> str:
        return self.source.split("/", 2)[0]

    @property
    def namespace(self) -> str:
        return self.source.split("/", 2)[1]

    @property
    def type_(self) -> str:
        return self.source.split("/", 2)[2]


def parse_lock_file(text: str) -> list[ProviderBlock]:
    """Pull every `provider "..." { ... }` block out of the lock file."""
    blocks: list[ProviderBlock] = []
    for m in _PROVIDER_BLOCK_RE.finditer(text):
        source = m.group("source")
        body = m.group("body")
        ver_m = _VERSION_RE.search(body)
        if ver_m is None:
            logger.warning("lock-file provider has no version line; skipping", source=source)
            continue
        # The full block text includes the close brace.
        whole = text[m.start() : m.end()]
        blocks.append(
            ProviderBlock(
                source=source,
                version=ver_m.group("version"),
                block_text=whole,
                block_start=m.start(),
                block_end=m.end(),
            )
        )
    return blocks


def fetch_h1_hashes(
    cfg_api_url: str,
    auth_token: str,
    block: ProviderBlock,
    platforms: list[str],
    *,
    client: httpx.Client | None = None,
    timeout_seconds: float = 60.0,
) -> tuple[dict[str, str], set[str]]:
    """Query Terrapod's provider mirror for `{version}.json` and pull
    the `h1:` hash for each requested platform.

    Returns `(hashes, cached_platforms)`:
      - `hashes`: `{platform: "h1:..."}` for each platform the mirror
        had an h1 for.
      - `cached_platforms`: the set of platforms the mirror is
        configured to eagerly cache (operator's `provider_cache.platforms`
        setting). Used by the caller to distinguish "h1 missing because
        compute failed → fall back to `providers lock`" from "h1 missing
        because this platform isn't in the operator's cache filter →
        silently skip (no apply will run on this arch anyway)".
    """
    if not cfg_api_url:
        return {}, set()

    url = (
        f"{cfg_api_url.rstrip('/')}/v1/providers/"
        f"{block.hostname}/{block.namespace}/{block.type_}/{block.version}.json"
    )
    headers = {"Authorization": f"Bearer {auth_token}"} if auth_token else {}

    own_client = client is None
    if client is None:
        client = httpx.Client(timeout=httpx.Timeout(timeout_seconds, connect=10.0))
    try:
        try:
            resp = client.get(url, headers=headers)
        except httpx.RequestError as exc:
            logger.warning(
                "mirror metadata fetch failed",
                source=block.source,
                version=block.version,
                err=str(exc),
            )
            return {}, set()
        if resp.status_code != 200:
            logger.info(
                "mirror returned non-200 for provider metadata",
                source=block.source,
                version=block.version,
                status=resp.status_code,
            )
            return {}, set()
        payload = resp.json()
    finally:
        if own_client:
            client.close()

    archives = payload.get("archives", {})
    cached_platforms = set(payload.get("cached_platforms") or [])
    out: dict[str, str] = {}
    for plat in platforms:
        entry = archives.get(plat)
        if not entry:
            continue
        for h in entry.get("hashes", []):
            if isinstance(h, str) and h.startswith("h1:"):
                out[plat] = h
                break
    return out, cached_platforms


def splice_hashes_into_block(block_text: str, new_hashes: list[str]) -> str:
    """Insert new `h1:` lines into a provider block's `hashes = [...]`
    list. Idempotent: hashes already present are not re-added.

    Preserves the indentation of the existing entries — we look at the
    line right after the `hashes = [` opener.
    """
    if not new_hashes:
        return block_text

    open_m = _HASHES_OPEN_RE.search(block_text)
    if open_m is None:
        # Block has no hashes list (shouldn't happen on a tofu-generated
        # lock file, but tolerate). Skip — splicing into a missing list
        # would require restructuring the block.
        return block_text

    # tofu indents list entries 4 spaces past the `hashes` keyword.
    base_indent = open_m.group("indent")
    entry_indent = base_indent + "  "

    # Find existing entries to dedupe.
    existing = set(re.findall(r'"([^"]+)"', block_text))
    fresh = [h for h in new_hashes if h not in existing]
    if not fresh:
        return block_text

    inject = "".join(f'{entry_indent}"{h}",\n' for h in fresh)
    insert_at = open_m.end()
    return block_text[:insert_at] + inject + block_text[insert_at:]


def extend_lock_file(
    lock_path: Path,
    *,
    api_url: str,
    auth_token: str,
    other_arch: str,
    client: httpx.Client | None = None,
) -> tuple[int, int]:
    """Read `lock_path`, query the mirror for the OTHER arch's h1 per
    provider, splice it into the file, write back.

    Returns `(providers_seen, providers_handled)` where `handled`
    counts providers we either successfully spliced OR knowingly
    skipped because the operator's `provider_cache.platforms` config
    doesn't include `other_arch` (i.e. no future apply will land on
    that arch, so no splice is needed). The caller uses
    `providers_seen - providers_handled` to decide whether to fall
    back to `tofu providers lock` for the gap — and that gap now
    excludes deliberate config-driven skips.
    """
    if not lock_path.exists():
        logger.info("no lock file — nothing to extend", path=str(lock_path))
        return 0, 0

    text = lock_path.read_text()
    blocks = parse_lock_file(text)
    if not blocks:
        return 0, 0

    own_client = client is None
    if client is None:
        client = httpx.Client(timeout=httpx.Timeout(60.0, connect=10.0))

    extended = 0
    not_cached_by_config = 0
    new_text = text
    try:
        # We iterate in REVERSE so splice offsets stay valid as we
        # rewrite the text from end to start.
        for block in reversed(blocks):
            hashes, cached_platforms = fetch_h1_hashes(
                api_url,
                auth_token,
                block,
                [other_arch],
                client=client,
            )
            h1 = hashes.get(other_arch)
            if h1 is None:
                # Two cases: operator has deliberately not configured
                # the mirror to cache this arch (silent skip — no apply
                # will run on it anyway), or the platform IS in the
                # cache config but the mirror failed to compute h1
                # (warn + caller falls back to `providers lock`).
                if cached_platforms and other_arch not in cached_platforms:
                    not_cached_by_config += 1
                else:
                    logger.info(
                        "no h1 from mirror for provider — caller may fall back to providers lock",
                        source=block.source,
                        version=block.version,
                        platform=other_arch,
                    )
                continue
            spliced = splice_hashes_into_block(block.block_text, [h1])
            if spliced == block.block_text:
                # Hash already present — already extended on a prior plan.
                extended += 1
                continue
            new_text = new_text[: block.block_start] + spliced + new_text[block.block_end :]
            extended += 1
    finally:
        if own_client:
            client.close()

    if not_cached_by_config:
        logger.info(
            "skipped h1 splice for platform not in mirror's cache config",
            platform=other_arch,
            providers_skipped=not_cached_by_config,
        )
        # Count config-driven skips as "handled" — the caller's gap
        # math (`seen - handled`) should NOT trigger the expensive
        # `tofu providers lock` fallback in this case, because no apply
        # will ever land on `other_arch` anyway.
        extended += not_cached_by_config

    if new_text != text:
        lock_path.write_text(new_text)
        logger.info(
            "extended lock file with mirror-supplied h1 hashes",
            providers_extended=extended,
            providers_total=len(blocks),
            arch=other_arch,
        )

    return len(blocks), extended


def detect_other_arch() -> str | None:
    """Mirror the runner-entrypoint.sh OTHER_PLATFORM rule:
    aarch64 → linux_amd64
    x86_64  → linux_arm64
    anything else → None (skip the extension)
    """
    machine = platform.machine()
    if machine == "aarch64":
        return "linux_amd64"
    if machine == "x86_64":
        return "linux_arm64"
    return None


def main(argv: list[str] | None = None) -> int:
    """`python -m terrapod.runner.lock_extender [--lock PATH] [--arch PLATFORM]`

    Defaults: lock = .terraform.lock.hcl in CWD; arch = detected
    other-arch from `uname -m`. Reads TP_API_URL and TP_AUTH_TOKEN
    from env to find the mirror.

    Exit code:
      0 — every provider in the lock got its `h1:` for the other arch.
      0 with logged gaps — mirror had partial coverage; caller decides
      to fall back to `tofu providers lock` for the remainder.
    """
    import argparse
    import os
    import sys

    structlog.configure(
        processors=[
            structlog.contextvars.merge_contextvars,
            structlog.processors.add_log_level,
            structlog.processors.TimeStamper(fmt="iso", utc=True),
            structlog.dev.ConsoleRenderer(colors=False),
        ],
        wrapper_class=structlog.make_filtering_bound_logger(20),
        cache_logger_on_first_use=True,
    )

    parser = argparse.ArgumentParser(prog="python -m terrapod.runner.lock_extender")
    parser.add_argument("--lock", default=".terraform.lock.hcl")
    parser.add_argument("--arch")
    ns = parser.parse_args(argv if argv is not None else sys.argv[1:])

    api_url = os.environ.get("TP_API_URL", "")
    auth_token = os.environ.get("TP_AUTH_TOKEN", "")
    if not api_url:
        logger.info("TP_API_URL not set — nothing to do")
        return 0

    other_arch = ns.arch or detect_other_arch()
    if other_arch is None:
        logger.info("runner arch not aarch64/x86_64 — skipping lock extension")
        return 0

    seen, extended = extend_lock_file(
        Path(ns.lock),
        api_url=api_url,
        auth_token=auth_token,
        other_arch=other_arch,
    )
    gap = seen - extended
    if gap:
        logger.info(
            "lock extension incomplete; bash should fall back to "
            "`tofu providers lock` for uncached providers",
            providers_seen=seen,
            providers_extended=extended,
            providers_missing=gap,
        )
        # Non-zero exit signals "couldn't cover everything". Bash uses
        # this to decide whether to run the (expensive) full-archive
        # download fallback. When this exits 0, the mirror covered
        # every provider — no archive downloads needed.
        return 2
    return 0


if __name__ == "__main__":
    import sys

    sys.exit(main())
