"""Plan-phase workspace-diff snapshot + apply-phase restore.

Each phase of a Terrapod run runs in a fresh K8s Job with its own
workspace directory. That means anything plan generates on disk
(`data.archive_file` output zips, `null_resource` local-exec outputs,
etc.) is gone by the time apply starts — even though the tfplan
records references to those exact file paths. Apply then fails with
"open ...: no such file or directory" when the AWS / etc. provider
tries to read those files for resource creation.

This module bridges that gap by snapshotting the workspace file tree
at two points:

  1. After `tofu init` + lock-extender + lock upload, BEFORE plan
     (so init's per-arch downloads and the lock-extender's writes are
     baseline, not delta).
  2. After `tofu plan -out=tfplan` succeeds.

The set difference (paths in #2 but not in #1) is exactly the set of
files plan generated. That set gets tar'd up and uploaded as
`plan-artifacts`. Apply phase downloads it (404 = no diff, just
proceed) and extracts it over its initialised workspace, AFTER its
own `tofu init -lockfile=readonly` runs. `tofu apply tfplan` then
sees the same on-disk artifacts plan saw, and succeeds.

Set difference (not mtime / hash comparison) because terraform/tofu
plan only creates files; it does not modify or delete existing ones.
init owns lock/provider/module mutation; plan owns generated outputs.
A simple existence-based XOR captures exactly what we need.

Always excluded from the snapshot:

  * `tfplan` — uploaded via its own dedicated artifact endpoint.
  * `.terraform.lock.hcl` — uploaded via its own dedicated artifact
    endpoint, and modified between init and plan by the lock-extender
    so it would otherwise not show up in a pure-existence diff anyway.
  * `.terraform/terraform.tfstate` — init's metadata file. Apply
    re-runs init and writes its own (with apply-pod-specific provider
    install paths); restoring plan's would clobber apply's.
"""

from __future__ import annotations

import os
import tarfile
from pathlib import Path

import structlog

logger = structlog.get_logger("runner.plan_artifacts")


# Paths (relative to workspace root) we never include in the snapshot.
# tfplan + lock-file have dedicated artifact endpoints; the init-state
# metadata is rewritten by apply's own init.
_EXCLUDED_PATHS: frozenset[str] = frozenset(
    {
        "tfplan",
        ".terraform.lock.hcl",
        ".terraform/terraform.tfstate",
    }
)


def snapshot_paths(workspace: Path) -> set[str]:
    """Walk `workspace` and return the set of relative paths of every
    regular file present.

    Excludes the well-known artefacts in `_EXCLUDED_PATHS` so the diff
    that consumes the snapshot is automatically clean of them. Symlinks
    and special files are skipped — only regular files are tracked
    (matches what apply needs to restore + what tarfile portably
    preserves across hosts).
    """
    out: set[str] = set()
    for root, _dirs, files in os.walk(workspace):
        for f in files:
            full = Path(root) / f
            # Skip symlinks (their target may or may not be sensible
            # across the plan→apply boundary; we don't pretend to
            # restore them).
            try:
                if full.is_symlink() or not full.is_file():
                    continue
            except OSError:
                continue
            rel = str(full.relative_to(workspace))
            if rel in _EXCLUDED_PATHS:
                continue
            out.add(rel)
    return out


def compute_diff(post_init: set[str], post_plan: set[str]) -> set[str]:
    """Files generated by plan = files that exist after plan but didn't
    after init.

    Pure set difference (no mtime or hash check) — terraform/tofu plan
    only creates files; init owns lock/provider/module mutation. If
    plan ever started rewriting existing init outputs, that change
    would need a different diff strategy; until then, existence is
    sufficient and cheaper.
    """
    return post_plan - post_init


def tar_files(
    workspace: Path,
    relpaths: set[str],
    out_path: Path,
) -> int:
    """Write `relpaths` (relative to `workspace`) into a plain tar at
    `out_path`. Returns the resulting tarball's size in bytes.

    Plain tar (no compression) — the workspace diff is usually small
    (KB to a few MB for archive_file outputs) and adding gzip just
    pulls in a runtime dependency without buying meaningful savings
    at this scale. The API enforces the size cap on receipt; the
    runner reports the size via this return value so callers can log
    or skip the upload when the cap is known to be exceeded.
    """
    # Always produce a valid tar even when `relpaths` is empty — opening
    # then closing a tarfile in `w` mode writes the two EOF zero-blocks
    # (1024 bytes total) which posix tar readers (including the apply
    # phase's `extract_over`) accept as a zero-member archive. The
    # always-present upload simplifies the apply contract: a download
    # 404 means a real "where's the plan?" failure rather than the
    # ambiguous "either no diff OR an older runner".
    with tarfile.open(out_path, mode="w") as tf:
        for rel in sorted(relpaths):
            src = workspace / rel
            try:
                tf.add(src, arcname=rel, recursive=False)
            except OSError as exc:
                # Best-effort — a single unreadable file shouldn't
                # poison the whole snapshot. Apply may then fail on
                # the resource that needed it, which is no worse than
                # the pre-feature behaviour.
                logger.warning(
                    "plan-artifact tar add failed (skipping file)",
                    path=str(src),
                    err=str(exc),
                )
    return out_path.stat().st_size


def extract_over(tar_path: Path, workspace: Path) -> int:
    """Extract a plan-artifacts tarball into `workspace`, overlaying any
    existing files. Returns the number of regular files extracted.

    Path-traversal guarded: members whose resolved path lies outside
    `workspace` are skipped + logged. Matches the safety check used in
    `summariser._build_code_diff`'s tarball extraction path.
    """
    if not tar_path.exists() or tar_path.stat().st_size == 0:
        return 0

    workspace = workspace.resolve()
    extracted = 0
    with tarfile.open(tar_path, mode="r") as tf:
        for member in tf.getmembers():
            if not member.isreg():
                # We only ever write regular files (see tar_files), so
                # a non-regular member here is anomalous — skip it.
                continue
            target = (workspace / member.name).resolve()
            try:
                target.relative_to(workspace)
            except ValueError:
                logger.warning(
                    "plan-artifact tar member escapes workspace (skipped)",
                    name=member.name,
                )
                continue
            target.parent.mkdir(parents=True, exist_ok=True)
            src = tf.extractfile(member)
            if src is None:
                continue
            with open(target, "wb") as dst:
                while True:
                    buf = src.read(1024 * 1024)
                    if not buf:
                        break
                    dst.write(buf)
            extracted += 1
    return extracted
