"""Generate `terrapod.auto.tfvars` from workspace terraform variables.

Terrapod injects `category=terraform` workspace variables by writing them to a
generated `*.auto.tfvars` file in the working directory (the way HCP Terraform /
TFE does), rather than as `TF_VAR_*` environment variables. This matters for
complex values: an `object`/`list`/`map` value round-trips identically on both
`terraform` and `tofu` through a tfvars file, whereas `TF_VAR_` env parsing of
complex values is type-dependent and diverges between the two engines for
untyped variables.

Formatting follows the `hcl` flag, matching TFE semantics:
  - ``hcl=True``  → the value is written as a **raw HCL expression**
                    (`key = <value>`), e.g. lists, maps, objects, numbers.
  - ``hcl=False`` → the value is written as a **quoted string literal**
                    (`key = "<escaped>"`), so a literal that happens to look
                    like HCL (`"[a, b]"`) stays a string.

Precedence note: an `*.auto.tfvars` file takes precedence over a committed
`terraform.tfvars` in the repo, so a Terrapod workspace variable now wins over a
same-named repo default (this matches HCP Terraform / TFE).
"""

from __future__ import annotations

import json
from pathlib import Path

import structlog

log = structlog.get_logger("runner.phases.tfvars")

# Distinctive name so it never collides with a user's own *.auto.tfvars.
_FILENAME = "terrapod.auto.tfvars"


def render_tfvars(terraform_vars: list[dict]) -> str:
    """Render the terraform variables as the body of an HCL `.tfvars` file.

    Each item is ``{key, value, hcl}``. ``hcl`` values are emitted verbatim as
    HCL expressions; non-``hcl`` values are JSON-encoded into a quoted string
    literal (valid HCL, correctly escaped).
    """
    lines = ["# Generated by Terrapod from workspace variables. Do not edit."]
    for var in terraform_vars:
        key = var.get("key")
        if not key:
            continue
        value = var.get("value", "")
        if var.get("hcl"):
            # Raw HCL expression (list/map/object/number/bool/...).
            lines.append(f"{key} = {value}")
        else:
            # Literal string — json.dumps gives a valid, escaped HCL string.
            lines.append(f"{key} = {json.dumps(str(value))}")
    return "\n".join(lines) + "\n"


def write_auto_tfvars(cwd: Path, terraform_vars: list[dict]) -> Path | None:
    """Write `terrapod.auto.tfvars` into ``cwd``. Returns the path, or None when
    there are no terraform variables (no file written)."""
    if not terraform_vars:
        return None
    path = cwd / _FILENAME
    path.write_text(render_tfvars(terraform_vars), encoding="utf-8")
    log.info(
        "wrote terraform variables",
        path=str(path),
        count=len(terraform_vars),
    )
    return path
